=== nguyenhongphat0/phatflower/web/WEB-INF/xsd/plants.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           targetNamespace="http://phatflower.vn"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="plants">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="plant" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="price" type="xs:decimal"></xs:element>
                            <xs:element name="link" type="xs:string"></xs:element>
                            <xs:element name="image" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nguyenhongphat0/phatflower/web/WEB-INF/xsd/plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<plants xmlns="http://phatflower.vn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://phatflower.vn plants.xsd">
    <plant>
        <name>Cây đại lộc</name>
        <price>900000</price>
        <link>https://cayvahoa.net/cay-dai-loc/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-dai-loc-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây kim ti?n</name>
        <price>690000</price>
        <link>https://cayvahoa.net/cay-kim-tien-hop-tuoi/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-kim-tien-2-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây l??i c?p</name>
        <price>700000</price>
        <link>https://cayvahoa.net/cay-luoi-cop/</link>
        <image>https://cayvahoa.net/wp-content/uploads/Cay-luoi-cop-3-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây bàng Singapore</name>
        <price>550000</price>
        <link>https://cayvahoa.net/cay-bang-singapore/</link>
        <image>https://cayvahoa.net/wp-content/uploads/Cay-bang-Singapore-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây thi?t m?c lan</name>
        <price>700000</price>
        <link>https://cayvahoa.net/ban-cay-thiet-moc-lan-tai-ha-noi/</link>
        <image>https://cayvahoa.net/wp-content/uploads/thiet-moc-lan-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây v?n niên thanh leo c?t</name>
        <price>700000</price>
        <link>https://cayvahoa.net/cay-van-nien-thanh-leo-cot/</link>
        <image>https://cayvahoa.net/wp-content/uploads/Cay-van-nien-thanh-leo-cot-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây kim ngân xo?n</name>
        <price>600000</price>
        <link>https://cayvahoa.net/san-don-cay-kim-ngan-xoan/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-kim-ngan-that-bim-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây c? nh?t</name>
        <price>350000</price>
        <link>https://cayvahoa.net/cay-co-nhat/</link>
        <image>https://cayvahoa.net/wp-content/uploads/chau-cay-co-nhat-dep-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây m?c h??ng</name>
        <price>1000000</price>
        <link>https://cayvahoa.net/cay-moc-huong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-moc-huong-300x300.png</image>
    </plant>
    <plant>
        <name>C? nhung nh?t</name>
        <price>65000</price>
        <link>https://cayvahoa.net/co-nhung-nhat/</link>
        <image>https://cayvahoa.net/wp-content/uploads/co-nhung-nhat-co-nhat-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây m? két</name>
        <price>35000</price>
        <link>https://cayvahoa.net/cay-mo-ket/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-chuoi-mo-ket-3-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa lan t?i</name>
        <price>150000</price>
        <link>https://cayvahoa.net/cay-hoa-lan-toi/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-hoa-lan-toi-3-300x300.jpg</image>
    </plant>
    <plant>
        <name>C? lá tre, c? lá g?ng</name>
        <price>10000</price>
        <link>https://cayvahoa.net/co-la-tre-co-la-gung/</link>
        <image>https://cayvahoa.net/wp-content/uploads/co-la-tre-co-la-gung-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây lim x?t</name>
        <price>1</price>
        <link>https://cayvahoa.net/cay-lim-xet/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-lim-xet-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây mu?ng hoa vàng</name>
        <price>1</price>
        <link>https://cayvahoa.net/cay-muong-hoa-vang/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-muong-hoa-vang-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây s?u</name>
        <price>1</price>
        <link>https://cayvahoa.net/cay-sau/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-sau-300x300.png</image>
    </plant>
    <plant>
        <name>Hoa cúc h?a mi</name>
        <price>200000</price>
        <link>https://cayvahoa.net/hoa-cuc-hoa-mi/</link>
        <image>https://cayvahoa.net/wp-content/uploads/hoa-cuc-hoa-mi-300x300.jpg</image>
    </plant>
    <plant>
        <name>Hoa cát t??ng</name>
        <price>120000</price>
        <link>https://cayvahoa.net/hoa-cat-tuong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/hoa-cat-tuong-1-300x300.jpg</image>
    </plant>
    <plant>
        <name>Hoa h??ng d??ng</name>
        <price>90000</price>
        <link>https://cayvahoa.net/cay-hoa-huong-duong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/trong-hoa-huong-duong-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa thu h?i ???ng</name>
        <price>200000</price>
        <link>https://cayvahoa.net/cay-hoa-thu-hai-duong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cach-trong-va-cham-soc-chau-hoa-thu-hai-duong-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa mào gà</name>
        <price>39000</price>
        <link>https://cayvahoa.net/cay-hoa-mao-ga/</link>
        <image>https://cayvahoa.net/wp-content/uploads/hoa-mao-ga-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây s?n tùng</name>
        <price>300000</price>
        <link>https://cayvahoa.net/cay-son-tung/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-son-tung-1-300x300.png</image>
    </plant>
    <plant>
        <name>Cây hoa ng?c n?</name>
        <price>169000</price>
        <link>https://cayvahoa.net/cay-hoa-ngoc-nu/</link>
        <image>https://cayvahoa.net/wp-content/uploads/Cay-hoa-ngoc-nu-2-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa nh? ý cát t??ng</name>
        <price>130000</price>
        <link>https://cayvahoa.net/cay-hoa-nhu-y-cat-tuong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2017/02/hoa-nhu-y-cat-tuong-3-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây ?? v??ng</name>
        <price>450000</price>
        <link>https://cayvahoa.net/cay-de-vuong/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-de-vuong-van-phong-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây chu?i c?nh</name>
        <price>450000</price>
        <link>https://cayvahoa.net/cay-chuoi-canh/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-chuoi-canh-1-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây lan tuy?t</name>
        <price>550000</price>
        <link>https://cayvahoa.net/cay-lan-tuyet/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-lan-tuyet-2-300x300.jpeg</image>
    </plant>
    <plant>
        <name>Cây saphia / h?ng di?p môn</name>
        <price>460000</price>
        <link>https://cayvahoa.net/ban-cay-saphia-hong-diep-mon-y-nghia-tien-tai-va-suc-khoe/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2016/09/cay-saphia-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây cau Hawai</name>
        <price>499000</price>
        <link>https://cayvahoa.net/y-nghia-cham-soc-ban-cay-cau-hawai/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2016/09/16010292_1618383151511320_732240845_o-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây h??ng th?o – Rosemary</name>
        <price>150000</price>
        <link>https://cayvahoa.net/cay-huong-thao/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2016/02/cây-h??ng-th?o-??p-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây kim ti?n</name>
        <price>600000</price>
        <link>https://cayvahoa.net/cay-kim-tien/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2016/02/cay-kim-tien-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây kim ngân</name>
        <price>250000</price>
        <link>https://cayvahoa.net/cay-kim-ngan/</link>
        <image>https://cayvahoa.net/wp-content/uploads/2016/02/12769561_1277895132226792_582058226_n-1-300x300.jpg</image>
    </plant>
    <plant>
        <name>Hoa cúc h?a mi</name>
        <price>200000</price>
        <link>https://cayvahoa.net/hoa-cuc-hoa-mi/</link>
        <image>https://cayvahoa.net/wp-content/uploads/hoa-cuc-hoa-mi-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa h?ng xanh</name>
        <price>350000</price>
        <link>https://cayvahoa.net/cay-hoa-hong-xanh/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-hoa-hong-xanh-3-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa h?ng anh</name>
        <price>99000</price>
        <link>https://cayvahoa.net/cay-hoa-hong-anh/</link>
        <image>https://cayvahoa.net/wp-content/uploads/day-leo-hoa-hong-anh-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa cúc indo</name>
        <price>150000</price>
        <link>https://cayvahoa.net/cay-hoa-cuc-indo/</link>
        <image>https://cayvahoa.net/wp-content/uploads/chau-cay-hoa-cuc-indo-trang-tri-cua-so-1-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa ngàn sao</name>
        <price>99000</price>
        <link>https://cayvahoa.net/cay-hoa-ngan-sao/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-hoa-ngan-sao-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa sen c?n</name>
        <price>140000</price>
        <link>https://cayvahoa.net/cay-hoa-sen-can/</link>
        <image>https://cayvahoa.net/wp-content/uploads/cay-hoa-sen-can-300x300.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa h?ng ??i màu</name>
        <price>250000</price>
        <link>https://cayvahoa.net/cay-hoa-hong-doi-mau/</link>
        <image>https://cayvahoa.net/wp-content/uploads/hoa-hong-doi-mau-3.jpg</image>
    </plant>
    <plant>
        <name>Cây hoa cúc vàng</name>
        <price>160000</price>
